name: Add reviewers to release PRs

on:
  pull_request_target:
    branches: ['master', 'next']
    types: ['labeled']

permissions: {}

jobs:
  add-reviewers:
    # Tests that label is added on the PR
    if: ${{ github.event.label.name == 'release' }}
    runs-on: ubuntu-latest
    env:
      ORG: ${{ github.event.organization }}
      # we can use the team slug when making this a reusable workflow
      TEAM_SLUG: x
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - id: get-members
        run: |
          DATA=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /orgs/$ORG/teams/$TEAM_SLUG/members?role=maintainer&per_page=100 \
            | jq 'reduce inputs as $i (.; . += $i)') \
          echo "data=$DATA" >> $GITHUB_OUTPUT

      # assign reviewers
      - id: assign-reviewers
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$ORG/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
            -d '{"reviewers":[${{ join(fromJson(steps.get-members.outputs.data).*.login) }}]}' \
